add datadog_additional_groups and datadog_use_local_repo switches
DataDog/ansible-datadog pull request #167
Opened 2018-11-28 11:41 UTC by okunc

This is to make DD deploy more flexible - two changes [switches] are proposed:

1] `datadog_use_local_repo` - Set to `true` only in case you have local repo with datadog sources. When set to true, repo is not handled at all - this assumes you have your e.g. satellite server already configured and containing the datadog rpm. This switch applies to yum repo management only.

comment: this may seem to interfere with these two [and I like them!] ..
- https://github.com/DataDog/ansible-datadog/pull/165
- https://github.com/DataDog/ansible-datadog/pull/166

.. but my proposal brings extra option to add DD user to other groups which may not be detected or which are simply out of scope of the auto-detection. E.g. you may need cassandra group to read debug logs etc.. In a way this could be also used to [test-only / edge cases / not recommended] add DD user to root group.

2] `datadog_additional_groups` - List of additional groups for `datadog_user`.

comment: this may seem to interfere with https://github.com/DataDog/ansible-datadog/pull/160 but my proposal is more flexible - pull request 160 allows only one group, while my update has a list

thanks a lot for coop / update and have a nice day all!
Ondrej

2018-11-28 12:01 UTC, okunc commented
Oops I messed up the commit message - all the referenced pull requests relate to my point 2.

2018-12-05 01:12 UTC, hush-hush requested changes
Thanks a lot for this PR @okunc !

The user/group parts seems like a very good idea.

For the `datadog_use_local_repo` I'm not sure I see the advantage compare to using the `*_repo` variables in default/main.yml.

Could you either split this PR in 2 or remove the part about `datadog_use_local_repo`, that way I can merge the group part !

2018-12-05 01:12 UTC, hush-hush commented on README.md
> +- `datadog_use_local_repo` - Set to `true` only in case you have local repo with datadog sources. When set to true, repo is not handled at all - this assumes you have your e.g. satellite server alrea
Why not use the `datadog_yum_repo` variable to set your own repo ?

2018-12-05 01:12 UTC, hush-hush commented on tasks/main.yml
> +  with_items: "{{ datadog_additional_groups }}"
`groups` can take a list directly, I don't think we need the `with_items`.

2019-05-06 14:28 UTC, dabcoder commented
@okunc Any feedback regarding the comments we made last year?

2019-05-16 08:16 UTC, dabcoder commented
Closing in favor of https://github.com/DataDog/ansible-datadog/pull/194 but thanks for the proposal and original work there.

2019-05-16 08:16 UTC, closed without merging

2019-07-29 21:41 UTC, okunc commented
> Closing in favor of #194 but thanks for the proposal and original work there.

sorry for late reply and thanks a lot for making this happen!