Releasing 3.0.0
DataDog/ansible-datadog pull request #186
Opened 2019-03-20 20:38 UTC by hush-hush

2019-03-20 20:42 UTC, derekwbrown approved these changes

2019-03-21 09:38 UTC, olivielpeau commented on CHANGELOG.md
> +- [FIX] Make sure the Live Process agent and APM agent aren't started when datadog_enabled is set to false (thanks to [@pdecat][]).
the links don't work :)

2019-04-15 15:45 UTC, rouge8 commented
Any plans to finish this release?

2019-05-12 13:01 UTC, dabcoder commented
> Any plans to finish this release?

Yes, apologies about the delay, we're planning on finish this very soon, I will update this thread asap.

2019-05-20 08:48 UTC, dabcoder requested changes

2019-05-20 08:48 UTC, dabcoder commented on CHANGELOG.md
> +- [FEATURE] On Unix: you can now add the Agent's user to additionnal groups.
Nit: Linux instead of Unix?

2019-05-20 14:37 UTC, merged