Adds Cloud Workfload Security agent configuration
DataDog/ansible-datadog pull request #375
Opened 2021-07-06 17:01 UTC by alsmola

This change adds the Cloud Workload Security agent configuration described here: https://docs.datadoghq.com/security_platform/cloud_workload_security/getting_started/

I haven't tested this, but I'm hoping it's a good start for the DataDog devs to get into master so we can use this new feature.

2021-07-07 17:01 UTC, jtappa requested changes

2021-07-07 17:01 UTC, jtappa commented on README.md
> +| `datadog_agent_flavor`                     | Override the default Debian / Redhat Package for IOT Installations on RPI. Defaults to "datadog-agent" - use "datadog-iot-agent" for RPI.
I don't think you meant to remove this, it would break the table.
```suggestion
| `datadog_agent_flavor`                     | Override the default Debian / Redhat Package for IOT Installations on RPI. Defaults to "datadog-agent" - use "datadog-iot-agent" for RPI.   |
```

2021-07-14 14:25 UTC, bkabrda requested changes
Hi 👋 thanks a lot for sending this PR! It looks really good and works fine according to my testing. I just left one minor note inline about updating README. Once that's addressed, I can merge.

2021-07-14 14:25 UTC, bkabrda commented on README.md
>  **Note**: The system probe works on Linux with Agent v6+. NPM is supported on Windows with Agent v6.27+ and v7.27+.
Could you please also add a note here about the Cloud Workload Security being only supported on Linux and requiring Agent 6.27+/7.27+?

2021-07-14 16:46 UTC, alsmola commented on README.md
>  **Note**: The system probe works on Linux with Agent v6+. NPM is supported on Windows with Agent v6.27+ and v7.27+.
Done. Thanks!

2021-07-14 18:06 UTC, jtappa approved these changes

2021-07-15 07:03 UTC, bkabrda approved these changes

2021-07-15 07:04 UTC, bkabrda commented
Looks perfect now, I'm merging. Thanks again for your contribution!

2021-07-15 07:04 UTC, merged