Fix CentOS 5 related issues
DataDog/ansible-datadog pull request #48
Opened 2017-02-27 21:39 UTC by Holmser

This PR fixes the issues outlined in [Issue 47](https://github.com/DataDog/ansible-datadog/issues/47).  There is a breaking change as `sha256sum` was deprecated for `checksum` in 2.0.

* [IMPROVEMENT] sha256sum is deprecated per [Ansible documentation](http://docs.ansible.com/ansible/get_url_module.html).  SHA1 is the only universal option across all versions, so it was chosen.
* [FEATURE] Allow APT repo setting to be user defined.

2017-03-01 20:18 UTC, olivielpeau requested changes
Thanks for your contribution @Holmser!

I've added a few comments, let me know what you think

2017-03-01 20:18 UTC, olivielpeau commented on CHANGELOG.md
> +# 1.3.0 / 2017-2-27
Could you remove the release date? (since it won't be the actual release date ;) )

`Unreleased` would work for instance

2017-03-01 20:18 UTC, olivielpeau commented on CHANGELOG.md
> +* [FEATURE] Allow APT repo setting to be user defined.
I think you meant `yum repo` instead

2017-03-01 20:18 UTC, olivielpeau commented on defaults/main.yml
> +datadog_yum_repo: "https://yum.datadoghq.com/rpm/"
you should use the value of the variable in the template: https://github.com/DataDog/ansible-datadog/blob/1.2.0/templates/datadog.repo.j2#L3-L6

2017-03-01 20:18 UTC, olivielpeau commented on meta/main.yml
> +  min_ansible_version: 2.0
Is there a way we could avoid increasing the minimum ansible version? Increasing it would require a major version bump on this role IMO.

2017-03-01 20:18 UTC, olivielpeau commented on tasks/pkg-redhat.yml
> +    checksum: sha1:19ae0b5ef027560202632581ba213702cf78be0f
could we make the algorithm depend on the platform so that we still use a `sha256` hash for platforms that support it?

2017-03-05 20:12 UTC, Holmser commented on CHANGELOG.md
> +# 1.3.0 / 2017-2-27
:+1:

2017-03-05 20:12 UTC, Holmser commented on CHANGELOG.md
> +* [FEATURE] Allow APT repo setting to be user defined.
:+1:

2017-03-05 20:13 UTC, Holmser commented on defaults/main.yml
> +datadog_yum_repo: "https://yum.datadoghq.com/rpm/"
fixed

2017-09-29 13:43 UTC, irabinovitch commented
@Holmser any thoughts on @olivielpeau 's feedback?

2017-09-29 18:28 UTC, jeffwidman requested changes
Why is a `.pyc` file included in this PR?

Also, IMHO adding `Molecule`, while it may (or may not) be a good idea, is a significant change that should probably be in a separate PR so it can be discussed separately from the CentOS 5 issues.

2019-05-13 08:10 UTC, dabcoder commented
Closing this as per @hush-hush's comment here: https://github.com/DataDog/ansible-datadog/issues/47#issuecomment-388933544, CentOS 5 being EOL and whilst we're considering the use of Molecule for this role, it would be good to evaluate it in a separate PR as pointed out in the previous comment.

2019-05-13 08:10 UTC, closed without merging