Refactor integration-related tasks
DataDog/ansible-datadog pull request #483
Opened 2023-05-15 12:16 UTC by bkabrda

This change makes the code tidier and user-facing messages prettier. It also ensures that Windows tasks will only be imported on Windows, thus making the ansible.windows collection optional.

This fixes #450.

2023-05-15 12:33 UTC, chouetz requested changes
I guess at least the correction on calling the macos file on top condition must be changed, thanks in advance

2023-05-15 12:33 UTC, chouetz commented on tasks/integration.yml
> +  include_tasks: integration/macos.yml
```suggestion
  include_tasks: integration/linux.yml
```

2023-05-15 12:33 UTC, chouetz commented on tasks/integration/windows.yml
> +  when: ansible_facts.os_family == "Windows"
This (and the other when conditions mentioning "Windows") are unnecessary as already checked to call this file, correct?

2023-05-15 12:33 UTC, chouetz commented on tasks/integration/windows.yml
> +  when: item.value.action == "remove" and ansible_facts.os_family == "Windows"
```suggestion
  when: item.value.action == "remove"
```

2023-05-15 12:33 UTC, chouetz commented on tasks/integration/windows.yml
> +  when: item.value.action == "install" and ansible_facts.os_family == "Windows"
```suggestion
  when: item.value.action == "install"
```

2023-05-15 14:22 UTC, bkabrda commented on tasks/integration/windows.yml
> +  when: ansible_facts.os_family == "Windows"
Yes, I forgot to remove the conditions from this file, thanks for pointing it out!

2023-05-16 13:56 UTC, chouetz approved these changes
LGTM!

2023-05-17 06:47 UTC, merged