Add support for compliance_config
DataDog/ansible-datadog pull request #488
Opened 2023-06-05 09:24 UTC by daisukixci

2023-06-06 08:07 UTC, bkabrda requested changes
Hi :wave: thanks for the PR. The functionality itself looks fine, but could you please document this new value in the `README.md` section here: https://github.com/DataDog/ansible-datadog#system-probe to make sure it's discoverable? Thanks!

2023-06-07 08:47 UTC, daisukixci commented
> Hi wave thanks for the PR. The functionality itself looks fine, but could you please document this new value in the `README.md` section here: https://github.com/DataDog/ansible-datadog#system-probe to make sure it's discoverable? Thanks!

Added, let me know if you need something else

2023-06-07 11:02 UTC, bkabrda requested changes
:wave: just one minor suggestion to address, then I can approve and merge. Thanks!

2023-06-07 11:02 UTC, bkabrda commented on README.md
> +[Compliance][] is configured under the `compliance_config` variable. Any variables nested underneath are written to the `security-agent.yaml`, in the `compliance_config` section.
```suggestion
[Compliance][18] is configured under the `compliance_config` variable. Any variables nested underneath are written to the `security-agent.yaml`, in the `compliance_config` section.
```

2023-06-07 19:15 UTC, alai97 approved these changes
Looks good, one suggestion!

2023-06-07 19:15 UTC, alai97 commented on README.md
> +This is only available for Agent v6+.
```suggestion
This is only available for Agent v6 or later.
```

2023-06-08 07:55 UTC, bkabrda approved these changes

2023-06-08 08:39 UTC, merged